CREATE (orleans:STATION {name: "Orleans"}),
(aubrais:STATION {name:"Les Aubrais"}),
(blois:STATION {name:"Blois Chambord"}),
(chambord:STATION {name:"Chambord"}),
(tours:STATION {name:"Tours"}),
(amb:STATION {name:"Amboise"}),
(stp:STATION {name:"Saint Pierre-des-corps"}),
(rom:STATION {name:"Romorantin"}),
(vierzon:STATION {name:"Vierzon"}),
(montargis:STATION {name:"Montargis"}),
(bourges:STATION {name:"Bourges"}),
(chartres:STATION {name:"Chartres"}),
(paris1:STATION {name:"Paris Austerlitz", ville:"Paris"}),
(paris2:STATION {name:"Paris Montparnasse", ville:"Paris"}),
(etampes:STATION {name:"Etampes"}),

(orleans)-[:byTrain {type:"Remi", cp: 0, cost: 0} ]->(aubrais),
(aubrais)-[:byTrain {type:"Remi", cp: 2, cost: 4}]->(paris1),
(orleans)-[:byTrain {type:"Remi", cp: 1, cost: 2}]->(blois),
(blois)-[:byTrain {type:"Remi", cp: 1, cost: 2}]->(amb),
(amb)-[:byTrain {type:"Remi", cp: 1, cost: 2}]->(stp),
(stp)-[:byTrain {type:"Remi", cp: 0, cost: 0}]->(tours),
(orleans)-[:byTrain {type:"Remi", cp: 1, cost: 3}]->(chartres),
(aubrais)-[:byTrain {type:"Remi", cp: 1, cost: 3}]->(chartres),
(orleans)-[:byTrain{type:"Remi", cp: 2, cost: 3} ]->(montargis),
(aubrais)-[:byTrain {type:"Remi", cp: 2, cost: 3}]->(vierzon),
(vierzon)-[:byTrain {type:"Remi", cp: 2, cost: 3}]->(bourges),
(vierzon)-[:byTrain {type:"Remi", cp: 2, cost: 3}]->(rom),
(tours)-[:byTrain {type:"Remi", cp: 0, cost: 0}]->(stp),
(stp)-[:byTrain {type:"TGV", cp: 3, cost: 5}]->(paris2),
(paris1)-[:byTrain {type:"Remi", cp: 2, cost: 4}]->(orleans),
(paris1)-[:byTrain {type:"Remi", cp: 1, cost: 2}]->(etampes),
(etampes)-[:byTrain {type:"Remi", cp: 1, cost: 2}]->(orleans),

(orleans)-[:byTram {ligne: "A", cp: 1, cost: 1} ]->(aubrais),

(blois)-[:byBus {type:"BusTourism", cp: 2, cost: 1}]->(chambord),
(aubrais)-[:byBus {type:"BusSCNF",cp: 4, cost: 3}]->(paris1),
(aubrais)-[:byBus {type:"BusSCNF",cp: 3, cost: 3}]->(bourges),
(orleans)-[:byBus {type:"BusSCNF",cp: 3, cost: 2}]->(blois),
(orleans)-[:byBus {type:"BusSCNF",cp: 4, cost: 3}]->(tours),
(blois)-[:byBus {type:"BusSCNF",cp: 3, cost: 2}]->(tours),

(aubrais)-[:byCar {type:"blabla",cp: 5, cost: 4}]->(paris1),
(aubrais)-[:byCar {type:"blabla",cp: 5, cost: 4}]->(bourges),
(orleans)-[:byCar {type:"blabla",cp: 3, cost: 3}]->(blois),
(blois)-[:byCar {type:"blabla",cp: 3, cost: 3}]->(amb),
(amb)-[:byCar {type:"blabla",cp: 3, cost: 3}]->(stp),
(stp)-[:byCar {type:"blabla",cp: 2, cost: 1}]->(tours),
(paris2)-[:byMetro {ligne:"4",cp: 1, cost: 1}]->(paris1)
