CREATE (orleans:STATION {name: "Orleans",  ville:"Orleans" }),
(aubrais:STATION {name:"Les Aubrais",  ville:"Orleans"}),
(blois:STATION {name:"Blois Chambord", ville:"Blois"}),
(tours:STATION {name:"Tours",  ville:"Tours"}),
(amb:STATION {name:"Amboise", ville:"Amboise"}),
(stp:STATION {name:"Saint Pierre-des-corps",  ville:"Tours"}),
(paris1:STATION {name:"Paris Austerlitz", ville:"Paris"}),
(paris2:STATION {name:"Paris Montparnasse", ville:"Paris"}),
(etampes:STATION {name:"Etampes", ville:"Etampes"}),
(orleans)-[:byTrain {type:"Remi", cp: 0, cost: 0, HDep: 1,  HArr: 2} ]->(aubrais),
(aubrais)-[:byTrain {type:"Remi", cp: 2, cost: 4,  HDep: 3,  HArr: 6}]->(paris1),
(orleans)-[:byTrain {type:"Remi", cp: 1, cost: 2,  HDep: 3,  HArr: 4}]->(blois),
(blois)-[:byTrain {type:"Remi", cp: 1, cost: 2,  HDep: 2,  HArr: 3}]->(amb),
(amb)-[:byTrain {type:"Remi", cp: 1, cost: 2, HDep: 3,  HArr: 4}]->(stp),
(stp)-[:byTrain {type:"Remi", cp: 0, cost: 0, HDep: 4,  HArr: 5}]->(tours),
(stp)-[:byTrain {type:"TGV", cp: 3, cost: 5, HDep: 8,  HArr: 11}]->(paris2),
(paris1)-[:byTrain {type:"Remi", cp: 2, cost: 4,  HDep: 15,  HArr: 18}]->(orleans),
(paris1)-[:byTrain {type:"Remi", cp: 1, cost: 2, HDep: 15,  HArr: 17}]->(etampes),
(etampes)-[:byTrain {type:"Remi", cp: 1, cost: 2, HDep: 17,  HArr: 19}]->(orleans)