CREATE (d1:Drinker {name:'Nils', sexe:'M', age:30}),
(d2:Drinker {name:'Bob', sexe:'M', age:25}),
(d3:Drinker {name:'Alice', sexe:'F', age:26}),
(d4:Drinker {name:'Marie', sexe:'F', age:24}),
(d5:Drinker {name:'Tom', sexe:'M', age:30}),
(d6:Drinker {name:'Barbara', sexe:'F', age:30}),
(d7:Drinker {name:'Peter', sexe:'M', age:31}),
(d8:Drinker {name:'Agripine', sexe:'F', age:31}),
(d9:Drinker {name:'Marc', sexe:'M', age:42}),
(d10:Drinker {name:'Jane', sexe:'F', age:40}),

(b1:Beer {name: 'Antarctica', type: 'pilsen'}),
(b2:Beer {name: 'Corona', type: 'lager'}),
(b3:Beer {name: 'Guinness', type: 'stout'}),
(b4:Beer {name: 'Bohemia', type: 'pilsen'}),
(b5:Beer {name: 'Leffe', type: 'abbaye'}),
(b6:Beer {name: 'Grimbergen', type: 'abbaye'}),

(c1: Bar {name: 'Ipanema', city:'Orleans',  rating_hygiene:5, rating_service:3}),
(c2: Bar {name: 'Brasil', city:'Paris',  rating_hygiene:5, rating_service:5}),
(c3: Bar {name: 'Lilas', city:'Paris',  rating_hygiene:3, rating_service:4}),
(c4: Bar {name: 'La Gare', city:'Orleans',  rating_hygiene:3, rating_service:2}),
(c5: Bar {name: 'Le bouillon', city:'Paris',  rating_hygiene:3, rating_service:3}),
(c6: Bar {name: 'Le syndicat', city:'Paris',  rating_hygiene:5, rating_service:5}),
(c7: Bar {name: 'La Coupole', city:'Paris',  rating_hygiene:4, rating_service:5}),
(c8: Bar {name: 'Lipp', city:'Paris',  rating_hygiene:4, rating_service:5}),
(c9: Bar {name: 'La Closerie de Lilas', city:'Paris',  rating_hygiene:4, rating_service:5}),

(cat1:Category {name: 'hygiene'}),
(cat2:Category {name: 'service'}),

(d1) -[:Likes]-> (b1),
(d1) -[:Likes]-> (b4),
(d2) -[:Likes]-> (b4),
(d3) -[:Likes]-> (b3),
(d3) -[:Likes]-> (b2),
(d4) -[:Likes]-> (b1),
(d4) -[:Likes]-> (b2),
(d4) -[:Likes]-> (b3),
(d4) -[:Likes]-> (b4),
(d4) -[:Likes]-> (b5),
(d4) -[:Likes]-> (b6),
(d10) -[:Likes]-> (b6),
(d9) -[:Likes]-> (b5),
(d9) -[:Likes]-> (b6),
(d9) -[:Likes]-> (b3),
(d9) -[:Likes]-> (b6),
(d7) -[:Likes]-> (b2),
(d6) -[:Likes]-> (b6),
(d6) -[:Likes]-> (b1),

(c1) -[:Sells]-> (b1),
(c1) -[:Sells]-> (b2),
(c1) -[:Sells]-> (b4),
(c2) -[:Sells]-> (b1),
(c2) -[:Sells]-> (b2),
(c2) -[:Sells]-> (b4),
(c3) -[:Sells]-> (b2),
(c4) -[:Sells]-> (b3),
(c5) -[:Sells]-> (b2),
(c5) -[:Sells]-> (b3),
(c6) -[:Sells]-> (b5),
(c6) -[:Sells]-> (b6),
(c7) -[:Sells]-> (b5),
(c7) -[:Sells]-> (b6),
(c8) -[:Sells]-> (b5),
(c8) -[:Sells]-> (b6),
(c9) -[:Sells]-> (b5),
(c9) -[:Sells]-> (b6),
(c9) -[:Sells]-> (b3),

(d1) -[:Goes {startYear:2022, weekF:4}]-> (c1),
(d1) -[:Goes {startYear:2021, weekF:2}]-> (c3),
(d2) -[:Goes {startYear:2020, weekF:3}]-> (c1),
(d2) -[:Goes {startYear:2022, weekF:2}]-> (c3),
(d1) -[:Goes {startYear:2023, weekF:4}]-> (c2),
(d3) -[:Goes {startYear:2021, weekF:5}]-> (c2),
(d4) -[:Goes {startYear:2021, weekF:6}]-> (c2),
(d8) -[:Goes {startYear:2021, weekF:2}]-> (c4),
(d7) -[:Goes {startYear:2021, weekF:2}]-> (c4),
(d9) -[:Goes {startYear:2021 ,weekF:7}]-> (c7),
(d10) -[:Goes {startYear:2021 ,weekF:7}]-> (c8),
(d10) -[:Goes {startYear:2021 ,weekF:7}]-> (c9),

(d1)-[:FriendOf]->(d2),
(d2)-[:FriendOf]->(d3),
(d3)-[:FriendOf]->(d6),
(d3)-[:FriendOf]->(d7),
(d6)-[:FriendOf]->(d7),
(d5)-[:FriendOf]->(d4),
(d4)-[:FriendOf]->(d5),
(d3)-[:FriendOf]->(d10),
(d6)-[:FriendOf]->(d9)
